import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Event(BaseModel):
    id: str = Field(default_factory=lambda: f"evt_{uuid.uuid4().hex[:12]}")
    type: str
    source: str = "api"
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    payload: Dict[str, Any]
    context: Dict[str, Any] = Field(default_factory=dict)
    priority: int = 5
    requires_response: bool = True
    schema_version: str = "1.0"


class TaskResultContract(BaseModel):
    """Declared before execution. Defines what 'success' means for this task."""
    success_criteria: List[str]        # e.g. ["page loaded", "screenshot saved"]
    required_tools: List[str] = []     # tools that MUST be called
    forbidden_tools: List[str] = []    # tools that MUST NOT be called
    max_steps: int = 10
    timeout_seconds: int = 120


class Task(BaseModel):
    id: str = Field(default_factory=lambda: f"task_{uuid.uuid4().hex[:12]}")
    title: str
    status: str = "running"
    goal: str
    created_from_event: str
    steps: List[Dict] = Field(default_factory=list)
    risk: str = "low"
    owner_agent: str = "eiros"
    requires_approval: bool = False
    result_contract: Optional[TaskResultContract] = None
    plan: Optional[List[str]] = None   # steps generated by planner


class ToolCall(BaseModel):
    type: str = "tool.call"
    tool: str
    args: Dict[str, Any]


class MemoryWrite(BaseModel):
    type: str
    content: str
    tags: List[str] = Field(default_factory=list)
    importance: int = 5


class Reflection(BaseModel):
    what_i_did: str
    result: str
    next_behavior_change: Optional[str] = None


class AgentOutput(BaseModel):
    mode: str = "act"                   # act | answer | wait
    message: str
    actions: List[ToolCall] = Field(default_factory=list)
    memory_writes: List[MemoryWrite] = Field(default_factory=list)
    reflection: Reflection
    confidence: float = 0.8
    needs_user: bool = False
    reason: Optional[str] = None
    question: Optional[str] = None


class PlannerOutput(BaseModel):
    plan: List[str]                     # ordered list of steps in natural language
    result_contract: TaskResultContract
    risk: str = "low"                   # low | medium | high
    rationale: str
